"""empty message

Revision ID: 5fcdec9e5867
Revises: 54adb681b567
Create Date: 2025-02-18 12:51:32.977777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcdec9e5867'
down_revision = '54adb681b567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('mass',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('mass',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
